---
title: "Giotto_macs_tcells_plotting"
author: "Inga-Maria"
date: "2023-12-05"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
#For Supplementary Figure 3c-e

library(dplyr)
library(tidyr)
library(readxl)
library(data.table)
library(circlize)
library(RColorBrewer)
library(ComplexHeatmap)

#load Interaction Cganhed Feature data (computed using the Giotto package) and annotations
list_ICF <- list()

for( i in c("s01","s02","s03","s05","s06",'s07', "s08", "s09", "s11", "s12", "s13", "s14", "s15", "s16", "s17", "s18", "s19", "s20", "s21", "s22", "s23")){
  
  list_ICF[[i]] <- read.csv(paste0("D:/sciset/giottoICF/Giotto_merged_myeloids2_",i,".csv"))
  
}


for( i in c("s01","s02","s03","s05","s06",'s07', "s08", "s09", "s11", "s12", "s13", "s14", "s15", "s16", "s17", "s18", "s19", "s20", "s21", "s22", "s23")){
  
  list_ICF[[i]]$imageid <- names(list_ICF[i])
  
}


data <- do.call(rbind.data.frame, list_ICF)

clinical <- read.csv("P:/h345/afarkkilab/Projects/Sciset/clinical_data.csv")

data$p_cat <- "sig"
data[which(data$p.adj > 0.05), "p_cat"] <- "not_sig"

data_merged <- merge(data, clinical[, c(2, 4, 5, 6, 7, 9, 10, 13)], by="imageid")

data_merged <- data_merged[which(data_merged$paired_patient== T),]

```




```{r}

list_p_paired <- list()

#p-values paired Wilcox test between chemo-naive and IDS samples

for ( i in unique(data_merged$spec_int)){
  for (j in c("MHCI", "MHCII", "SNAT1", "Ki67", "HE4", "Annexin", "pSTAT1")){
    tryCatch({ 
    
    data_merged_tumor_paired <- data_merged[which(data_merged$spec_int == i & data_merged$feats == j  & data_merged$Paired == TRUE ),]
 
  int <- data_merged_tumor_paired[which(data_merged_tumor_paired$Stage == "interval"),c("log2fc", "Patient.x")]
  prim <- data_merged_tumor_paired[which(data_merged_tumor_paired$Stage == "primary"), c("log2fc", "Patient.x")]
  
  int <- int[order(match(int$Patient.x, prim$Patient.x)),]
  
  test <- wilcox.test(int$log2fc, prim$log2fc, p.adjust.method = 'none', paired = T)
  list_p_paired <- append(list_p_paired, test$p.value)
  names(list_p_paired)[length(list_p_paired)] <- paste0(i,j)
  
  }, error=function(e){cat("ERROR :",conditionMessage(e), "\n")})
  }}




```





```{r}
test2 <- as.data.frame(list_p_paired)

test2 <- t(test2)

test2 <- as.data.frame(test2)

print(row.names(test2[which(test2$V1 < 0.05),,drop=F]))


```



```{r}

#test2 has p-values

  
mean_fc <- data_merged[which(data_merged$Paired == T),] %>% group_by(Stage, spec_int, feats) %>% summarise(mean_fc=mean(log2fc)) 
#merge spec_int ja feats
#pivot wider stage
mean_fc$feature <- paste0(mean_fc$spec_int, "_", mean_fc$feats)
mean_fc <- pivot_wider(mean_fc[, c(1, 3, 4, 5)], names_from = "Stage", values_from = "mean_fc")

#
#only include macrophages first

mean_fc <- mean_fc[mean_fc$feature %like% "Macrophages_", ]
mean_fc <- mean_fc[-which(mean_fc$feature %like% "Macrophages--"), ]
mean_fc <- mean_fc[-which(mean_fc$feature %like% "FOXOA3"), ]
mean_fc <- mean_fc[-which(mean_fc$feature %like% "HE4"), ]
mean_fc <- mean_fc[-which(mean_fc$feature %like% "TAZ"), ]
mean_fc <- mean_fc[-which(mean_fc$feature %like% "Macrophages_TIM3"), ]
mean_fc <- mean_fc[mean_fc$feature %like% "CD8.T.", ]

#col_c <- colorRamp2(c(-0.1, -0.05, 0.50, 0.1), c( "#0000FF","#AAAAFF", "#F9AAAA", "#EE0000"))
mean_fc <- as.data.frame(mean_fc)
rownames(mean_fc) <- mean_fc$feature
#mean_fc <- mean_fc[, c(1, 4, 3)]


#same but order CD8+T-cell subtypes


test <- setNames(c(moma.colors("Koons", "6")), c("Annexin", "MHCI", "MHCII", "SNAT1", "pSTAT1", "Ki67"))
colours<- list("feats"=test)
ann <- as.data.frame(mean_fc[,c(1)])
colnames(ann) <- "feats"
Rowann <- HeatmapAnnotation(df=ann, which="row", col=colours, 
                            annotation_name_gp = gpar(fontsize=10,fontface = "bold"), gap = unit(1, "mm"))

col_c <- colorRamp2(c(-0.1, 0, 0.05), hcl_palette = "Blue-Red 3")

column_split = rep("CD8.T.cells", 24)
column_split[7:12] = "pSTAT1.CD8.T.cells"
column_split[13:18] = "TIM3.CD8.T.cells"
column_split[19:24] = "pSTAT1.TIM3.CD8.T.cells"

hmap <- Heatmap(as.matrix(mean_fc[, c("primary","interval")]), name="log2fc interaction\n vs no-interaction", 
                row_names_gp = gpar(fontsize = 8),clustering_method_rows ="ward.D2",column_names_gp = gpar(fontsize = 10),column_title_gp = gpar(fontsize = 10, fontface = "bold"),cluster_columns = F, cluster_rows = F,
                left_annotation = Rowann, row_dend_width = unit(1.3, "cm"),show_row_names = T, row_title_gp = gpar(fontsize = 10, fontface = "bold"),
                show_row_dend=T, show_column_dend=T, column_title = "subtypes", row_title = "Samples",
                border="black", width = unit(1.3, "cm"),
                rect_gp = gpar(col = "white", lwd = 2), col=col_c, row_split = column_split)


draw(hmap)



```





```{r}
#then for tumor

mean_fc <- data_merged[which(data_merged$Paired == T),] %>% group_by(Stage, spec_int, feats) %>% summarise(mean_fc=mean(log2fc)) 
#
library(data.table)
#

mean_fc <- mean_fc[-which(mean_fc$spec_int %like% "Bcell"), ]
mean_fc <- mean_fc[-which(mean_fc$spec_int %like% "Stroma"), ]
mean_fc <- mean_fc[-which(mean_fc$spec_int %like% "CD4"), ]
mean_fc <- mean_fc[which(mean_fc$spec_int %like% "CD8"), ]
mean_fc <- mean_fc[-which(mean_fc$spec_int %like% "--CD8"), ]
mean_fc <- mean_fc[-which(mean_fc$spec_int %like% "--TIM3"), ]
mean_fc <- mean_fc[-which(mean_fc$spec_int %like% "--pSTAT1"), ]
mean_fc <- mean_fc[-which(mean_fc$spec_int %like% "CD11c"), ]
mean_fc <- mean_fc[-which(mean_fc$spec_int %like% "Endothelial"), ]
mean_fc <- mean_fc[-which(mean_fc$feats %like% "FOXOA3"), ]
mean_fc <- mean_fc[-which(mean_fc$feats %like% "HE4"), ]
mean_fc <- mean_fc[-which(mean_fc$feats %like% "TIM3"), ]

library(stringr)

mean_fc[, c("neighbor", "source")] <- str_split_fixed(mean_fc$spec_int, "--", 2)
#pivot wider stage
mean_fc$feature <- paste0(mean_fc$spec_int, "_", mean_fc$feats)
mean_fc <- pivot_wider(mean_fc[, c(1, 3, 4, 5, 6, 7)], names_from = "Stage", values_from = "mean_fc")

#then pivot wider macs ja tumor
mean_fc <- pivot_wider(mean_fc[, c(1,2,3,5,6)], names_from = "source", values_from = interval:primary)

mean_fc$feature <- paste0(mean_fc$neighbor, "_to_", mean_fc$feats)



colours<- list("feats"=c("Annexin"="#d8537dff","Ki67" ="#b5282aff","MHCI" ="#82aea7ff","MHCII"= "#bac88eff","pSTAT1"= "#6e2418ff", "SNAT1"= "#b3874eff","TAZ"= "#F16667","TIM3"= "#E62F27"), "neighbor"=c("CD8.T.cells"="#ef7923", "pSTAT1_CD8.T.cell"="#75bca9", "TIM3_CD8.T.cell" = "#7b89bb", "TIM3_pSTAT1_CD8.T.cell" ="#e9de97" ))
ann <- as.data.frame(mean_fc[,c(1, 2)])
colnames(ann) <- c("feats", "neighbor")
Rowann <- HeatmapAnnotation(df=ann, which="row", col=colours, 
                            annotation_name_gp = gpar(fontsize=10,fontface = "bold"), gap = unit(1, "mm"))

col_c <- colorRamp2(c(-0.1, 0, 0.3), hcl_palette = "Blue-Red 3")

mean_fc <- as.data.frame(mean_fc)
rownames(mean_fc) <- mean_fc$feature


#now only tumor
col_c <- colorRamp2(c(-0.1, 0, 0.2), hcl_palette = "Blue-Red 3")

column_split = rep("CD8.T.cells", 28)
column_split[8:14] = "pSTAT1.CD8.T.cells"
column_split[15:21] = "TIM3.CD8.T.cells"
column_split[22:28] = "pSTAT1.TIM3.CD8.T.cells"


hmap <- Heatmap(as.matrix(mean_fc[, c( "primary_Tumor", "interval_Tumor")]), name="log2fc interaction\n vs no-interaction", 
                row_names_gp = gpar(fontsize = 8),cluster_rows = F,clustering_method_rows ="ward.D2",column_names_gp = gpar(fontsize = 10),column_title_gp = gpar(fontsize = 10, fontface = "bold"),cluster_columns = F,
                left_annotation = Rowann, row_dend_width = unit(1.3, "cm"),show_row_names = T, row_title_gp = gpar(fontsize = 10, fontface = "bold"),
                show_row_dend=T, show_column_dend=T, column_title = "subtypes", row_title = "Samples",
                border="black", width = unit(1.3, "cm"),
                rect_gp = gpar(col = "white", lwd = 2), col=col_c, row_split=column_split)


draw(hmap)



```




